apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  Corefile: |-
    headquarter.svc.cluster.local:5353 { 
      forward . 10.0.0.37 
    }
    .:5353 { 
      forward . 10.100.0.10  
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      containers:
      - name: coredns
        image: coredns/coredns:1.6.6
        args:
        - '-conf'
        - '/etc/coredns/Corefile'
        ports:
        - name: dns
          containerPort: 5353
        volumeMounts:
        - name: config
          mountPath: /etc/coredns
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: coredns
---
apiVersion: v1
kind: Service
metadata:
  name: coredns
spec:
  selector:
    app: coredns
  ports:
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 5353
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 5353
