apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  Corefile: |-
    headquarter.svc.cluster.local:5353 { 
      forward . 10.0.0.37  
    }
    .:5353 { 
      forward . 172.16.0.15  
    }