apiVersion: v1
kind: Secret
metadata:
  name: cb-overseas-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: cGFzc3dvcmQ=         # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-acme-overseas
spec:
  image: couchbase/server:6.6.0
  security:
    adminSecret: cb-overseas-auth
  buckets:
    managed: true
  networking:
    exposeAdminConsole: true
    adminConsoleServices:
    - data
    adminConsoleServiceType: NodePort
    exposedFeatures:
    - xdcr
    - client
  platform: aws
  xdcr:
    managed: true
    remoteClusters:
    - name: acme-headquarter
      uuid: 328861165e6ae1e9c2995b3cfa1c7089 
      hostname: cb-acme-headquarter.headquarter 
      authenticationSecret: cb-xdcr-secret
      replications: 
        selector:
          matchLabels:
             replication: replicate-to-headquarter
  servers:
  - size: 3
    name: all_services
    services:
    - data
    - index
    - query
    - eventing
    pod:
      spec:
        dnsPolicy: None
        dnsConfig:
          nameservers:
            - "10.100.76.158"
          searches:
            - overseas.svc.cluster.local
            - svc.cluster.local
            - cluster.local
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: overseas-bucket
  labels:
    cluster: cb-acme-overseas
spec:
  memoryQuota: 100Mi
  replicas: 1
  enableFlush: true
  enableIndexReplica: true
  compressionMode: passive
---
apiVersion: couchbase.com/v2
kind: CouchbaseReplication
metadata:
  name: replicate-to-headquarter 
  labels:
    replication: replicate-to-headquarter 
spec:
  bucket: overseas-bucket
  remoteBucket: hq-bucket